var cadr;

function transcrire() {
    cadr = document.getElementById("cadr").value;

    cadr = cadr.replace(/==a/g, "ً");
    cadr = cadr.replace(/==i/g, "ٍ");
    cadr = cadr.replace(/==u/g, "ٌ");
    cadr = cadr.replace(/=a/g, "َ");
    cadr = cadr.replace(/=i/g, "ِ");
    cadr = cadr.replace(/=u/g, "ُ");
    cadr = cadr.replace(/=w/g, "ّ");
    cadr = cadr.replace(/=o/g, "ْ");
    cadr = cadr.replace(/’/g, "\'");
    cadr = cadr.replace(/[aâàā]/g, "ا");
    cadr = cadr.replace(/اا/g, "آ");
    cadr = cadr.replace(/b/g, "ب");
    cadr = cadr.replace(/ب'/g, "پ");
    cadr = cadr.replace(/p/g, "پ");
    cadr = cadr.replace(/پ'/g, "ب");
    cadr = cadr.replace(/t/g, "ت");
    cadr = cadr.replace(/ت'/g, "ث");
    cadr = cadr.replace(/ث'/g, "ت");
    cadr = cadr.replace(/ṯ/g, "ث");
    cadr = cadr.replace(/[jǧ]/g, "ج");
    cadr = cadr.replace(/ج'/g, "چ");
    cadr = cadr.replace(/c/g, "چ");
    cadr = cadr.replace(/چ'/g, "ح");
    cadr = cadr.replace(/[HḥḤ]/g, "ح");
    cadr = cadr.replace(/ح'/g, "خ");
    cadr = cadr.replace(/[xẖK]/g, "خ");
    cadr = cadr.replace(/خ'/g, "ج");
    cadr = cadr.replace(/d/g, "د");
    cadr = cadr.replace(/د'/g, "ذ");
    cadr = cadr.replace(/ذ'/g, "د");
    cadr = cadr.replace(/ḏ/g, "ذ");
    cadr = cadr.replace(/r/g, "ر");
    cadr = cadr.replace(/ر'/g, "ز");
    cadr = cadr.replace(/ز'/g, "ر");
    cadr = cadr.replace(/z/g, "ز");
    cadr = cadr.replace(/s/g, "س");
    cadr = cadr.replace(/س'/g, "ش");
    cadr = cadr.replace(/ش'/g, "س");
    cadr = cadr.replace(/š/g, "ش");
    cadr = cadr.replace(/[Sṣ]/g, "ص");
    cadr = cadr.replace(/ص'/g, "ض");
    cadr = cadr.replace(/ض'/g, "ص");
    cadr = cadr.replace(/[Dḍ]/g, "ض");
    cadr = cadr.replace(/[Tṭ]/g, "ط");
    cadr = cadr.replace(/ط'/g, "ظ");
    cadr = cadr.replace(/ظ'/g, "ط");
    cadr = cadr.replace(/[Zẓ]/g, "ظ");
    cadr = cadr.replace(/[gʿ]/g, "ع");
    cadr = cadr.replace(/ع'/g, "غ");
    cadr = cadr.replace(/غ'/g, "ع");
    cadr = cadr.replace(/ġ/g, "غ");
    cadr = cadr.replace(/f/g, "ف");
    cadr = cadr.replace(/ف'/g, "ڤ");
    cadr = cadr.replace(/ڤ'/g, "ف");
    cadr = cadr.replace(/v/g, "ڢ");
    cadr = cadr.replace(/q/g, "ق");
    cadr = cadr.replace(/ق'/g, "ڨ");
    cadr = cadr.replace(/ڨ'/g, "ق");
    cadr = cadr.replace(/k/g, "ك");
    cadr = cadr.replace(/ك'/g, "ڭ");
    cadr = cadr.replace(/ڭ'/g, "ك");
    cadr = cadr.replace(/l/g, "ل");
    cadr = cadr.replace(/m/g, "م");
    cadr = cadr.replace(/n/g, "ن");
    cadr = cadr.replace(/h/g, "ه");
    cadr = cadr.replace(/ه'/g, "ة");
    cadr = cadr.replace(/ة'/g, "ه");
    cadr = cadr.replace(/[wouôûōū]/g, "و");
    cadr = cadr.replace(/و'/g, "ؤ");
    cadr = cadr.replace(/ؤ'/g, "و");
    cadr = cadr.replace(/[yieîī]/g, "ي");
    cadr = cadr.replace(/[YIE]/g, "ى");
    cadr = cadr.replace(/ي'/g, "ى");
    cadr = cadr.replace(/ى'/g, "ئ");
    cadr = cadr.replace(/ئ'/g, "ي");
    cadr = cadr.replace(/-/g, "ء");
    cadr = cadr.replace(/ʾ/g, "ء");
    cadr = cadr.replace(/وءء/g, "ؤ");
    cadr = cadr.replace(/يءء/g, "ئ");
    cadr = cadr.replace(/اءء/g, "إ");
    cadr = cadr.replace(/I/g, "إ");
    cadr = cadr.replace(/A/g, "إ");
    cadr = cadr.replace(/ءا/g, "أ");
    cadr = cadr.replace(/_/g, "ـ");
    cadr = cadr.replace(/\?/g, "؟");
    cadr = cadr.replace(/\;/g, "؛");
    cadr = cadr.replace(/\,/g, "،");
    cadr = cadr.replace(/0=/g, "٠");
    cadr = cadr.replace(/1=/g, "١");
    cadr = cadr.replace(/2=/g, "٢");
    cadr = cadr.replace(/3=/g, "٣");
    cadr = cadr.replace(/4=/g, "٤");
    cadr = cadr.replace(/5=/g, "٥");
    cadr = cadr.replace(/6=/g, "٦");
    cadr = cadr.replace(/7=/g, "٧");
    cadr = cadr.replace(/8=/g, "٨");
    cadr = cadr.replace(/9=/g, "٩");
    cadr = cadr.replace(/%=/g, "٪");

    document.getElementById("cadr").value = cadr;

    var obj = document.getElementById("cadr");
    obj.focus();
    obj.scrollTop = obj.scrollHeight;
}

document.addEventListener("DOMContentLoaded", function () {
    var textarea = document.getElementById("cadr");
    textarea.addEventListener("input", transcrire);
});
